# modules/contabo.nix
# Contabo-specific NixOS configuration.
# Do not edit this file — put customizations in user.nix instead.
{ pkgs, ... }: {

  # --- Image format ---
  image.format = "qcow2";
  image.efiSupport = false;   # Contabo VPS uses SeaBIOS (BIOS/MBR), not UEFI
  image.baseName = "nixos";   # produces result/nixos.qcow2 (not a versioned name)

  # --- Disk ---
  virtualisation.diskSize = 8192;  # 8 GiB in MiB; qcow2 is sparse

  # --- VirtIO drivers: required by Contabo ---
  boot.initrd.availableKernelModules = [
    "virtio_scsi"
    "virtio_net"
    "virtio_pci"
    "virtio_blk"
  ];

  # --- Networking ---
  # Use global DHCP so the image works regardless of NIC name (eth0, ens18, enp0s18, etc.)
  networking.useDHCP = true;
  # Disable cloud-init network management to avoid conflict with dhcpcd
  services.cloud-init.network.enable = false;

  # --- SSH ---
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "yes";

  # --- Cloud-init: Contabo injects SSH keys at first boot ---
  services.cloud-init.enable = true;

  # Required: set a hostname (cloud-init may override at first boot)
  networking.hostName = "contabo";

  # --- Console keyboard ---
  # Default: US layout. Switch to German at runtime: loadkeys de
  console.keyMap = "us";

  system.stateVersion = "25.05";
}
