# modules/contabo.nix
# Contabo-specific NixOS configuration.
# Do not edit this file — put customizations in user.nix instead.
{ pkgs, ... }: {

  # --- Image format ---
  image.format = "qcow2";
  image.efiSupport = false;   # Contabo VPS uses SeaBIOS (BIOS/MBR), not UEFI
  image.baseName = "nixos";   # produces result/nixos.qcow2 (not a versioned name)

  # --- Disk ---
  virtualisation.diskSize = 8192;  # 8 GiB in MiB; qcow2 is sparse

  # --- VirtIO drivers: required by Contabo ---
  boot.initrd.availableKernelModules = [
    "virtio_scsi"
    "virtio_net"
    "virtio_pci"
    "virtio_blk"
  ];

  # --- Networking ---
  # Contabo delivers network config (IP, gateway) via cloud-init from the NoCloud
  # seed on /dev/sr0 — not via DHCP. Let cloud-init configure the interface and
  # disable dhcpcd to prevent it from overwriting the cloud-init-assigned address.
  networking.useDHCP = false;
  services.cloud-init.network.enable = true;

  # --- SSH ---
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "prohibit-password";

  # --- Cloud-init: Contabo injects SSH keys at first boot ---
  services.cloud-init.enable = true;

  # NixOS defaults cloud-init users to [root] only.
  # Adding "default" tells cloud-init to also process the default_user (admin),
  # which allows set_passwords to apply the Contabo portal password to admin.
  # Without "default" in this list, set_passwords warns "no default or defined user".
  services.cloud-init.settings = {
    users = [ "default" "root" ];
    system_info = {
      default_user = {
        name = "admin";
        lock_passwd = false;
      };
    };
  };

  # Required: set a hostname (cloud-init may override at first boot)
  networking.hostName = "contabo";

  # --- Console keyboard ---
  # Default: US layout. Switch to German at runtime: loadkeys de
  console.keyMap = "us";

  system.stateVersion = "25.11";
}
